import type { Metadata } from 'next';
import { inter, roboto_mono } from '@/app/font';
import './globals.css';
import Cursor from '@/components/ui/Cursor';

export const metadata: Metadata = {
  title: "Ryann's Next.js Project",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${roboto_mono.variable} font-sans`}>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
